//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbbaSoft.Dts
{
    using System;
    using System.Collections.Generic;
    
    public partial class detial
    {
        public int id { get; set; }
        public Nullable<int> idpro { get; set; }
        public Nullable<int> idinv { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<int> qtyinv { get; set; }
        public Nullable<double> amount { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual product product { get; set; }
    }
}
